name: dolphin-app
region: nyc
services:
- build_command: pip install -r requirements.txt
  environment_slug: python
  github:
    branch: master
    deploy_on_push: true
    repo: SlyyCooper/agenAI
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: agenai
  run_command: python3 main.py
  source_dir: /
  routes:
  - path: /ws
    preserve_path_prefix: true
  - path: /
    preserve_path_prefix: true
  envs:
  - key: API_DOMAIN
    scope: RUN_AND_BUILD_TIME
    value: dolphin-app-49eto.ondigitalocean.app
  - key: FRONTEND_DOMAIN
    scope: RUN_AND_BUILD_TIME
    value: agenai.app
  - key: BACKEND_URL
    scope: RUN_AND_BUILD_TIME
    value: https://dolphin-app-49eto.ondigitalocean.app
  - key: BACKEND_WS_URL
    scope: RUN_AND_BUILD_TIME
    value: wss://dolphin-app-49eto.ondigitalocean.app/ws
  - key: DEV_BACKEND_URL
    scope: RUN_AND_BUILD_TIME
    value: http://localhost:8000
  - key: ALLOWED_ORIGINS
    scope: RUN_AND_BUILD_TIME
    value: https://agenai.app,https://www.agenai.app,http://agenai.app,http://www.agenai.app,http://localhost:3000,https://dolphin-app-49eto.ondigitalocean.app
  - key: STRIPE_SUCCESS_URL
    scope: RUN_AND_BUILD_TIME
    value: https://www.agenai.app/success
  - key: STRIPE_CANCEL_URL
    scope: RUN_AND_BUILD_TIME
    value: https://www.agenai.app/cancel
  - key: PYTHON_VERSION
    scope: RUN_AND_BUILD_TIME
    value: "3.11.7"
features:
- buildpack-stack=ubuntu-22